# Generated by Django 5.0 on 2023-12-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_user_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
